### ISSUE TITLE
[Bug]Fatal error. System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by git-Charlie** [View12138/ViewFaceCore#79]
**简明描述**

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at ViewFaceCore.Native.ViewFaceNative.DisposeFaceDetector(IntPtr)
--------------------------------
   at ViewFaceCore.Core.FaceDetector.Dispose()
```

```
 at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback, System.Object, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)

```

```

 at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(System.Threading.Tasks.TaskCompletionSource, System.Threading.SendOrPostCallback, System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**重现步骤**

```

public sealed class MyClass : IDisposable
{
    private readonly FaceDetector _faceDetector = new();
    private readonly FaceRecognizer _faceRecognizer = new();
    private readonly FaceLandmarker _faceMark = new();
    private readonly FaceQuality _quality = new();


   public void Dispose()
    {
        _faceDetector.Dispose();
        _faceRecognizer.Dispose();
        _faceMark.Dispose();
        _quality.Dispose();
    }
}

```
每次**Dispose**时候会引发此异常 ,
例如下面的代码，如果注释掉   **my.Dispose()** 则可以正常运行，反之则会引起此异常。
```
        using var my= new MyClass();
        var result = await my.DoSomethingAsync(anyData);
        //my.Dispose();
        return result ;
```

其中 **DoSomethingAsync** 是一段业务代码，大致顺序是：
```
_faceDetector.Detect
 _faceMark.Mark
_faceRecognizer.Extract
_quality.Detect
```

**开发环境**
```
 - <Project Sdk="Microsoft.NET.Sdk">
 -   <TargetFramework>net7.0</TargetFramework>
```

**相关包清单**
```
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
    <PackageReference Include="ViewFaceCore" Version="0.3.8" />
    <PackageReference Include="ViewFaceCore.all_models" Version="6.0.7" />
    <PackageReference Include="ViewFaceCore.Extension.SkiaSharp" Version="0.3.7" />
    <PackageReference Include="ViewFaceCore.runtime.win.x64" Version="6.0.7" />
```

**Comment by withsalt** [comment]
请问运行的操作系统是？

**Comment by git-Charlie** [comment]
> 请问运行的操作系统是？

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2021-‎04-‎11
操作系统内部版本	19045.2486
体验	Windows Feature Experience Pack 120.2212.4190.0
处理器	AMD Ryzen 7 1700X Eight-Core Processor            3.40 GHz
机带 RAM	64.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器

dotnet --version
7.0.102

**Comment by withsalt** [comment]
```
       using var my= new MyClass();
        var result = await my.DoSomethingAsync(anyData);
        //my.Dispose();
        return result ;
```

这段代码，如果不注释my.Dispose();将会释放两次my对象。麻烦确认下其他代码是否也是这个原因引起的

**Comment by git-Charlie** [comment]
> ```
>        using var my= new MyClass();
>         var result = await my.DoSomethingAsync(anyData);
>         //my.Dispose();
>         return result ;
> ```
> 
> 这段代码，如果不注释my.Dispose();将会释放两次my对象。麻烦确认下其他代码是否也是这个原因引起的
都是的，所以注释了那句

**Comment by withsalt** [comment]
嗯嗯，后续优化一下重复释放的问题
