### ISSUE TITLE
[Bug] WinXP系统实例化FaceDetector对象时程序崩溃

### ISSUE THREAD

**Issue by AlexanderArima** [View12138/ViewFaceCore#80]
**简明描述**
WinXP系统实例化FaceDetector对象时程序崩溃

**重现步骤**
```
Bitmap bitmap = VideoPlayer.GetCurrentVideoFrame(); // 获取摄像头画面 
if (bitmap == null)
{
    SingleCameraForm.Delay(10, null);
    FormHelper.SetPictureBoxImage(FacePictureBox, bitmap);
    continue;
}

FaceImage faceimage = bitmap.ToFaceImage();
try
{
    using (FaceDetector faceDetector = new FaceDetector())            --> 执行到这一行时出错
    {
        FaceInfo[] infos = faceDetector.Detect(faceimage);
```

**开发环境**
 - 目标框架: [e.g. .NET Framework 4.0,-windows XP,7,10 x86&x64]
 - 项目类型 [e.g. Windows窗体应用]

**相关包清单**
 - [e.g. ViewFaceCore 0.3.8]
 - [e.g. ViewFaceCore.model.face_detector 6.0.7]
 - [e.g. ViewFaceCore.model.face_landmarker_pts5 6.0.7]
 - [e.g. ViewFaceCore.runtime.win.x86 6.0.7]

**运行环境**
 - 操作系统: [e.g. Windows XP SP3 专业版]
 - 系统类型: [e.g. 32 位操作系统，虚拟机中的操作系统]
 - 处理器: [e.g. Intel(R) Core(TM) i5-5200H]

**错误信息**
Application: FaceCompare.Winform.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
at System.Environment.GetResourceFromDefault(System.String)
at System.Diagnostics.StackTrace.ToString(TraceFormat)
at System.Environment.GetStackTrace(System.Exception, Boolean)
at System.Exception.GetStackTrace(Boolean)
at System.Exception.get_StackTrace()
at FaceCompare.Winform.Common.Log4NetHelper.Error(System.Object, System.Exception)
at FaceCompare.Winform.Program.Application_ThreadException(System.Object, System.Threading.ThreadExceptionEventArgs)
at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
at System.Windows.Forms.Control.WndProcException(System.Exception)
at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
at FaceCompare.Winform.Program.Main()

**Comment by withsalt** [comment]
尝试安装：ViewFaceCore.runtime.win.vc

**Comment by AlexanderArima** [comment]
安装了这个库，但还是有那个问题，后来换成OpenCvSharp3抓拍了
